urls_dict = {
    'home_page': 'https://nbis.se/training',
    'course_pages': [
        "https://nbis.se/training/a-primer-on-cryo-em-data-processing-using-cryo-sparc-on-berze-li-us",
        "https://nbis.se/training/advanced-data-visualization-in-r",
        "https://nbis.se/training/course-1",
        "https://nbis.se/training/biomarker-discovery-from-theory-to-real-world-examples",
        "https://nbis.se/training/elixir-goblet-train-the-trainer",
        "https://nbis.se/training/epigenomics-data-analysis-from-bulk-to-single-cell",
        "https://nbis.se/training/fair-training-material-by-design",
        "https://nbis.se/training/ngsintro",
        "https://nbis.se/training/introduction-to-data-management-practices",
        "https://nbis.se/training/introduction-to-biostatistics-and-machine-learning",
        "https://nbis.se/training/biostatistics-and-machine-learning-ii",
        "https://nbis.se/training/neural-networks-and-deep-learning",
        "https://nbis.se/training/course",
        "https://nbis.se/training/omics-integration-and-systems-biology",
        "https://nbis.se/training/population-genomics-in-practice",
        "https://nbis.se/training/programming-formalisms",
        "https://nbis.se/training/r-programming-foundations-for-data-analysis",
        "https://nbis.se/training/python-programming-with-applications-to-bioinformatics",
        "https://nbis.se/training/raukr",
        "https://nbis.se/training/rn-aseq-data-analysis",
        "https://nbis.se/training/snakemake-byoc-bring-your-own-code-workshop",
        "https://nbis.se/training/single-cell-rn-aseq-data-analysis",
        "https://nbis.se/training/20",
        "https://nbis.se/training/tools-for-reproducible-research",
    ]
}
